# Generated by Django 4.2.26 on 2025-11-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuitsong',
            options={'verbose_name': 'Skladba pro masíčko', 'verbose_name_plural': 'Skladby pro masíčka'},
        ),
        migrations.AlterModelOptions(
            name='circuittraining',
            options={'ordering': ['-created_at'], 'verbose_name': 'Masíčko', 'verbose_name_plural': 'Masíčka'},
        ),
        migrations.AddField(
            model_name='circuittraining',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Veřejné'),
        ),
        migrations.AlterField(
            model_name='circuitsong',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='fencers.circuittraining', verbose_name='Masíčko'),
        ),
    ]
