# Generated by Django 4.2.26 on 2025-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0003_add_base_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('tournament', 'Turnaj'), ('humanitarian', 'Humanitní turnaj'), ('other', 'Ostatní akce')], default='other', max_length=20, verbose_name='Typ akce'),
        ),
    ]
