# Generated by Django 4.2.26 on 2025-11-26 11:45

from django.db import migrations, models
import django.db.models.deletion


def link_calendar_events(apps, schema_editor):
    Tournament = apps.get_model('fencers', 'Tournament')
    CalendarEvent = apps.get_model('fencers', 'CalendarEvent')

    tournament_events = CalendarEvent.objects.filter(event_type='tournament')

    for event in tournament_events:
        if not event.start_date:
            continue

        event_date = event.start_date.date()
        title_normalized = event.title.strip()

        tournament = Tournament.objects.filter(
            calendar_event__isnull=True,
            date=event_date,
            name__iexact=title_normalized,
        ).first()

        if tournament:
            tournament.calendar_event_id = event.id
            if not tournament.location and event.location:
                tournament.location = event.location
            tournament.save()
        else:
            Tournament.objects.create(
                calendar_event_id=event.id,
                name=event.title,
                date=event_date,
                location=event.location,
                is_internal=False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0004_calendarevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='calendar_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entry', to='fencers.calendarevent', verbose_name='Kalendářní akce'),
        ),
        migrations.RunPython(link_calendar_events, migrations.RunPython.noop),
    ]
