# Generated by Django 4.2.26 on 2025-11-26 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fencers', '0011_remove_is_internal_from_event'),
    ]

    operations = [
        # First, update the state to rename CalendarEvent to Event
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameModel(
                    old_name='CalendarEvent',
                    new_name='Event',
                ),
                # Update EventReaction to reference Event instead of CalendarEvent
                migrations.AlterField(
                    model_name='eventreaction',
                    name='event',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='fencers.event', verbose_name='Akce'),
                ),
            ],
        ),
        # Create PhotoAlbum model
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Obalová fotka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_album', to='fencers.event', verbose_name='Akce')),
            ],
            options={
                'verbose_name': 'Fotoalbum',
                'verbose_name_plural': 'Fotoalba',
                'ordering': ['-event__start_date'],
            },
        ),
        # Create SubAlbum model
        migrations.CreateModel(
            name='SubAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to='fencers.photoalbum', verbose_name='Album')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Subalbum',
                'verbose_name_plural': 'Subalba',
                'ordering': ['-created_at'],
            },
        ),
        # Add subalbum field to EventPhoto
        migrations.AddField(
            model_name='eventphoto',
            name='subalbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fencers.subalbum', verbose_name='Subalbum'),
        ),
    ]
