# Generated by Django 4.2.26 on 2025-11-26 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fencers', '0013_add_photolike'),
    ]

    operations = [
        # Only add the new fields to FencerProfile and make user nullable
        migrations.AddField(
            model_name='fencerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='fencerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Jméno'),
        ),
        migrations.AddField(
            model_name='fencerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='fencerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fencer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
    ]
