# Generated by Django 4.2.26 on 2025-11-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fencers', '0014_make_fencerprofile_user_nullable'),
    ]

    operations = [
        # EventParticipation already exists in the database (created via raw SQL in 0010)
        # This migration only updates Django's migration state, not the database
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes needed - table already exists
            state_operations=[
                migrations.CreateModel(
                    name='EventParticipation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('position', models.IntegerField(blank=True, null=True, verbose_name='Umístění')),
                        ('wins', models.IntegerField(default=0, verbose_name='Výhry')),
                        ('losses', models.IntegerField(default=0, verbose_name='Prohry')),
                        ('touches_scored', models.IntegerField(default=0, verbose_name='Zasazené zásahy')),
                        ('touches_received', models.IntegerField(default=0, verbose_name='Obdržené zásahy')),
                        ('fencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Šermíř')),
                        ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='fencers.event', verbose_name='Akce')),
                    ],
                    options={
                        'verbose_name': 'Účast na akci',
                        'verbose_name_plural': 'Účasti na akcích',
                        'ordering': ['-event__start_date'],
                        'unique_together': {('fencer', 'event')},
                    },
                ),
            ],
        ),
    ]
