# Generated by Django 4.2.26 on 2025-11-26 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fencers', '0015_sync_eventparticipation_state'),
    ]

    operations = [
        # Tournament and TournamentParticipation were already deleted from database via raw SQL in 0010
        # This migration only updates Django's migration state, not the database
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes needed - tables already deleted
            state_operations=[
                # Remove unique_together constraint from TournamentParticipation (state only)
                migrations.AlterUniqueTogether(
                    name='tournamentparticipation',
                    unique_together=set(),
                ),
                # Remove fields from TournamentParticipation (state only)
                migrations.RemoveField(
                    model_name='tournamentparticipation',
                    name='fencer',
                ),
                migrations.RemoveField(
                    model_name='tournamentparticipation',
                    name='tournament',
                ),
                # Update Event model options (state only - already done in database)
                migrations.AlterModelOptions(
                    name='event',
                    options={'ordering': ['start_date'], 'verbose_name': 'Akce', 'verbose_name_plural': 'Akce'},
                ),
                # Update Event.event_type field (state only - already done in database)
                migrations.AlterField(
                    model_name='event',
                    name='event_type',
                    field=models.CharField(choices=[('tournament', 'Turnaj'), ('humanitarian', 'Hum. turnaj'), ('other', 'Ostatní akce')], default='other', max_length=20, verbose_name='Typ akce'),
                ),
                # Delete Tournament and TournamentParticipation from state (already deleted from database)
                migrations.DeleteModel(
                    name='Tournament',
                ),
                migrations.DeleteModel(
                    name='TournamentParticipation',
                ),
            ],
        ),
    ]
