# Generated by Django 4.2.26 on 2025-11-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0017_change_to_fencerprofile_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('Z', 'Ž'), ('V', 'Vše')], default='V', max_length=1, verbose_name='Pohlaví'),
        ),
        migrations.AddField(
            model_name='fencerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('Z', 'Ž')], max_length=1, null=True, verbose_name='Pohlaví'),
        ),
    ]
