# Generated by Django 4.2.26 on 2025-11-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0018_event_gender_fencerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='payment_notified',
            field=models.BooleanField(default=False, verbose_name='Upozornění odesláno'),
        ),
    ]
