# Generated by Django 4.2.26 on 2025-11-27 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fencers', '0019_paymentstatus_payment_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nadpis')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Datum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Novinka',
                'verbose_name_plural': 'Novinky',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Přečteno')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='fencers.news', verbose_name='Novinka')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reads', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Přečtená novinka',
                'verbose_name_plural': 'Přečtené novinky',
                'ordering': ['-read_at'],
                'unique_together': {('news', 'user')},
            },
        ),
    ]
