# Generated by Django 4.2.26 on 2025-11-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0021_change_event_to_date_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Akce', 'verbose_name_plural': 'Akce'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'ordering': ['-event__date'], 'verbose_name': 'Účast na akci', 'verbose_name_plural': 'Účasti na akcích'},
        ),
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'ordering': ['-event__date'], 'verbose_name': 'Fotoalbum', 'verbose_name_plural': 'Fotoalba'},
        ),
    ]
