# Generated by Django 4.2.26 on 2025-11-30 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0025_change_user_to_fencerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fencers.fencerprofile', verbose_name='Nahrál'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fencers.fencerprofile', verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='subalbum',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fencers.fencerprofile', verbose_name='Vytvořil'),
        ),
    ]
