# Generated by Django 4.2.26 on 2025-12-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0026_alter_eventphoto_uploaded_by_alter_news_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fencerprofile',
            name='email',
        ),
    ]
