# Generated by Django 4.2.26 on 2025-12-02 00:14
# Modified to use raw SQL to avoid User model resolution issues

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0027_remove_email_from_fencerprofile'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE fencers_equipmentitem ADD COLUMN shop_5mfencing_link VARCHAR(200) DEFAULT ''",
                "ALTER TABLE fencers_equipmentitem ADD COLUMN shop_5mfencing_price DECIMAL(10, 2)",
                "ALTER TABLE fencers_equipmentitem ADD COLUMN shop_rubyfencing_link VARCHAR(200) DEFAULT ''",
                "ALTER TABLE fencers_equipmentitem ADD COLUMN shop_rubyfencing_price DECIMAL(10, 2)",
            ],
            reverse_sql=[
                # SQLite doesn't support DROP COLUMN directly, so we'll leave reverse empty
                # If rollback is needed, a new migration would be required
            ],
        ),
    ]
