# Generated by Django 4.2.26 on 2025-12-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fencers', '0028_add_shop_links_and_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='shop_5mfencing_link',
            field=models.URLField(blank=True, verbose_name='Odkaz 5MFencing'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='shop_5mfencing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena 5MFencing'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='shop_rubyfencing_link',
            field=models.URLField(blank=True, verbose_name='Odkaz Rubyfencing'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='shop_rubyfencing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena Rubyfencing'),
        ),
    ]
