# Generated by Django 4.2.26 on 2026-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0035_update_trainer_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='is_hall_of_fame',
            field=models.BooleanField(default=False, verbose_name='Síň slávy'),
        ),
    ]
