# Generated by Django 4.2.26 on 2026-04-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0037_equipment_boty_ponozky_kord_zalozni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tournament', 'Turnaj'), ('humanitarian', 'UŠL - univerzitní liga'), ('other', 'Ostatní akce')], default='other', max_length=20, verbose_name='Typ akce'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_count',
            field=models.IntegerField(blank=True, help_text='Povinné pro Turnaj a UŠL - univerzitní liga', null=True, verbose_name='Počet účastníků'),
        ),
    ]
