# Generated by Django 5.2.12 on 2026-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0041_content_block_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fencerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Profilová fotka'),
        ),
    ]
