# Generated by Django 4.2.30 on 2026-04-17 23:57

from django.db import migrations, models
import fencers.models


class Migration(migrations.Migration):

    dependencies = [
        ('fencers', '0045_contentpage_nav_tiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='tags',
            field=models.JSONField(blank=True, default=fencers.models._empty_tag_list, help_text='Libovolné krátké texty (např. jména na fotce); pro vyhledávání.', verbose_name='Štítky'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='tags_search',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Štítky (vyhledávání)'),
        ),
    ]
